name: Subways
version: '${project.version}'
main: dev.jensderuiter.subway.SubwayPlugin
authors: [ jensjeflensje ]
description: Subways/Trams in Minecraft
commands:
  subway:
    usage: /subway
    description: Main command for spawning and editing subway configurations.